/*
 * Cryptosat Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

export class CreateBallotResponse {
  constructor() {
  }

  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateBallotResponse();
      if (data.hasOwnProperty('ballot_id'))
        obj.ballotId = ApiClient.convertToType(data['ballot_id'], 'String');
    }
    return obj;
  }

  getBallotId() {
    return this.ballotId;
  }

  setBallotId(ballotId) {
    this.ballotId = ballotId;
  }

}

CreateBallotResponse.prototype.ballotId = undefined;

