/*
 * Cryptosat Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

export class GetResultResponse {
  constructor() {
  }

  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetResultResponse();
      if (data.hasOwnProperty('ballot_result'))
        obj.ballotResult = ApiClient.convertToType(data['ballot_result'], 'String');
    }
    return obj;
  }

  getBallotResult() {
    return this.ballotResult;
  }

  setBallotResult(ballotResult) {
    this.ballotResult = ballotResult;
  }

}

GetResultResponse.prototype.ballotResult = undefined;

