/*
 * Cryptosat Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

export class KeypairResponse {
  constructor() {
  }

  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new KeypairResponse();
      if (data.hasOwnProperty('keypair_id'))
        obj.keypairId = ApiClient.convertToType(data['keypair_id'], 'String');
    }
    return obj;
  }

  getKeypairId() {
    return this.keypairId;
  }

  setKeypairId(keypairId) {
    this.keypairId = keypairId;
  }

}

KeypairResponse.prototype.keypairId = undefined;

