/*
 * Cryptosat Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

export class NextOnlineResponse {
  constructor() {
  }

  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NextOnlineResponse();
      if (data.hasOwnProperty('next_online_s'))
        obj.nextOnlineS = ApiClient.convertToType(data['next_online_s'], 'Number');
    }
    return obj;
  }

  getNextOnlineS() {
    return this.nextOnlineS;
  }

  setNextOnlineS(nextOnlineS) {
    this.nextOnlineS = nextOnlineS;
  }

}

NextOnlineResponse.prototype.nextOnlineS = undefined;

