/*
 * Cryptosat Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

export class PrivateKeyResponse {
  constructor() {
  }

  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PrivateKeyResponse();
      if (data.hasOwnProperty('private_key'))
        obj.privateKey = ApiClient.convertToType(data['private_key'], 'String');
    }
    return obj;
  }

  getPrivateKey() {
    return this.privateKey;
  }

  setPrivateKey(privateKey) {
    this.privateKey = privateKey;
  }

}

PrivateKeyResponse.prototype.privateKey = undefined;

