/*
 * Cryptosat Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

export class PublicRandomResponse {
  constructor() {
  }

  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PublicRandomResponse();
      if (data.hasOwnProperty('randomness'))
        obj.randomness = ApiClient.convertToType(data['randomness'], 'String');
      if (data.hasOwnProperty('signature'))
        obj.signature = ApiClient.convertToType(data['signature'], 'String');
    }
    return obj;
  }

  getRandomness() {
    return this.randomness;
  }

  setRandomness(randomness) {
    this.randomness = randomness;
  }

  getSignature() {
    return this.signature;
  }

  setSignature(signature) {
    this.signature = signature;
  }

}

PublicRandomResponse.prototype.randomness = undefined;

PublicRandomResponse.prototype.signature = undefined;

