/*
 * Cryptosat Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

export class PublicKeysResponse {
  constructor() {
  }

  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PublicKeysResponse();
      if (data.hasOwnProperty('public_keys'))
        obj.publicKeys = ApiClient.convertToType(data['public_keys'], ['String']);
    }
    return obj;
  }

  getPublicKeys() {
    return this.publicKeys;
  }

  setPublicKeys(publicKeys) {
    this.publicKeys = publicKeys;
  }

}

PublicKeysResponse.prototype.publicKeys = undefined;

