/*
 * Cryptosat Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

export class RandomnessResponse {
  constructor() {
  }

  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RandomnessResponse();
      if (data.hasOwnProperty('random_numbers'))
        obj.randomNumbers = ApiClient.convertToType(data['random_numbers'], [OneOfRandomnessResponseRandomNumbersItems]);
    }
    return obj;
  }

  getRandomNumbers() {
    return this.randomNumbers;
  }

  setRandomNumbers(randomNumbers) {
    this.randomNumbers = randomNumbers;
  }

}

RandomnessResponse.prototype.randomNumbers = undefined;

