/*
 * Cryptosat Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

export class TimestampResponse {
  constructor() {
  }

  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TimestampResponse();
      if (data.hasOwnProperty('timestamp_ms'))
        obj.timestampMs = ApiClient.convertToType(data['timestamp_ms'], 'Number');
      if (data.hasOwnProperty('signature'))
        obj.signature = ApiClient.convertToType(data['signature'], 'String');
    }
    return obj;
  }

  getTimestampMs() {
    return this.timestampMs;
  }

  setTimestampMs(timestampMs) {
    this.timestampMs = timestampMs;
  }

  getSignature() {
    return this.signature;
  }

  setSignature(signature) {
    this.signature = signature;
  }

}

TimestampResponse.prototype.timestampMs = undefined;

TimestampResponse.prototype.signature = undefined;

