/*
 * Cryptosat Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {RandomnessResponse} from '../model/RandomnessResponse';


export class RandomBeaconApi {

    
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    randomnessGetWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'num': opts['num'],'type': opts['type'],'format': opts['format']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['RequestAuthorizer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = RandomnessResponse;

      return this.apiClient.callApi(
        '/randomness', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }
    randomnessGet(opts) {
      return this.randomnessGetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }

}