/*
 * Cryptosat Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.sandbox-sdk);
  }
}(this, function(expect, sandbox-sdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new sandbox-sdk.DelayEncryptionApi();
  });

  describe('(package)', function() {
    describe('DelayEncryptionApi', function() {
      describe('delayEncKeypairDelayPost', function() {
        it('should call delayEncKeypairDelayPost successfully', function(done) {
          // TODO: uncomment, update parameter values for delayEncKeypairDelayPost call and complete the assertions
          /*

          instance.delayEncKeypairDelayPost(delay).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(sandbox-sdk.KeypairResponse);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('delayEncKeypairsKeypairIdPrivateGet', function() {
        it('should call delayEncKeypairsKeypairIdPrivateGet successfully', function(done) {
          // TODO: uncomment, update parameter values for delayEncKeypairsKeypairIdPrivateGet call and complete the assertions
          /*

          instance.delayEncKeypairsKeypairIdPrivateGet(keypairId).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(sandbox-sdk.PrivateKeyResponse);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('delayEncKeypairsKeypairIdPublicGet', function() {
        it('should call delayEncKeypairsKeypairIdPublicGet successfully', function(done) {
          // TODO: uncomment, update parameter values for delayEncKeypairsKeypairIdPublicGet call and complete the assertions
          /*

          instance.delayEncKeypairsKeypairIdPublicGet(keypairId).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(sandbox-sdk.PublicKeyResponse);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
