/*
 * Cryptosat Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.sandbox-sdk);
  }
}(this, function(expect, sandbox-sdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new sandbox-sdk.RandomBeaconApi();
  });

  describe('(package)', function() {
    describe('RandomBeaconApi', function() {
      describe('randomnessGet', function() {
        it('should call randomnessGet successfully', function(done) {
          // TODO: uncomment, update parameter values for randomnessGet call and complete the assertions
          /*
          var opts = {};

          instance.randomnessGet(opts).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(sandbox-sdk.RandomnessResponse);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
