/*
 * Cryptosat Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.sandbox-sdk);
  }
}(this, function(expect, sandbox-sdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new sandbox-sdk.SatMetricsApi();
  });

  describe('(package)', function() {
    describe('SatMetricsApi', function() {
      describe('nextOnlineGet', function() {
        it('should call nextOnlineGet successfully', function(done) {
          // TODO: uncomment nextOnlineGet call and complete the assertions
          /*

          instance.nextOnlineGet().then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(sandbox-sdk.NextOnlineResponse);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('publicKeysGet', function() {
        it('should call publicKeysGet successfully', function(done) {
          // TODO: uncomment publicKeysGet call and complete the assertions
          /*

          instance.publicKeysGet().then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(sandbox-sdk.PublicKeysResponse);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('publicRandomGet', function() {
        it('should call publicRandomGet successfully', function(done) {
          // TODO: uncomment publicRandomGet call and complete the assertions
          /*

          instance.publicRandomGet().then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(sandbox-sdk.PublicRandomResponse);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('timestampGet', function() {
        it('should call timestampGet successfully', function(done) {
          // TODO: uncomment timestampGet call and complete the assertions
          /*

          instance.timestampGet().then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(sandbox-sdk.TimestampResponse);

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
