"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.MessageSigningApi = void 0;
var _ApiClient = require("../ApiClient");
var _SignMessageBody = require("../model/SignMessageBody");
var _SignMessageResponse = require("../model/SignMessageResponse");
var _StatusResponse = require("../model/StatusResponse");
function _typeof(obj) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (obj) { return typeof obj; } : function (obj) { return obj && "function" == typeof Symbol && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }, _typeof(obj); }
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, _toPropertyKey(descriptor.key), descriptor); } }
function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); Object.defineProperty(Constructor, "prototype", { writable: false }); return Constructor; }
function _toPropertyKey(arg) { var key = _toPrimitive(arg, "string"); return _typeof(key) === "symbol" ? key : String(key); }
function _toPrimitive(input, hint) { if (_typeof(input) !== "object" || input === null) return input; var prim = input[Symbol.toPrimitive]; if (prim !== undefined) { var res = prim.call(input, hint || "default"); if (_typeof(res) !== "object") return res; throw new TypeError("@@toPrimitive must return a primitive value."); } return (hint === "string" ? String : Number)(input); } /*
                                                                                                                                                                                                                                                                                                                                                                                               * Cryptosat Sandbox
                                                                                                                                                                                                                                                                                                                                                                                               * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               * OpenAPI spec version: 1.0.0
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                               * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               * Swagger Codegen version: 3.0.46
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               */
var MessageSigningApi = /*#__PURE__*/function () {
  function MessageSigningApi(apiClient) {
    _classCallCheck(this, MessageSigningApi);
    this.apiClient = apiClient || _ApiClient.ApiClient.instance;
  }
  _createClass(MessageSigningApi, [{
    key: "signMessagePostWithHttpInfo",
    value: function signMessagePostWithHttpInfo(body) {
      var postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling signMessagePost");
      }
      var pathParams = {};
      var queryParams = {};
      var headerParams = {};
      var formParams = {};
      var authNames = ['RequestAuthorizer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = _SignMessageResponse.SignMessageResponse;
      return this.apiClient.callApi('/sign-message', 'POST', pathParams, queryParams, headerParams, formParams, postBody, authNames, contentTypes, accepts, returnType);
    }
  }, {
    key: "signMessagePost",
    value: function signMessagePost(body) {
      return this.signMessagePostWithHttpInfo(body).then(function (response_and_data) {
        return response_and_data.data;
      });
    }
  }, {
    key: "signMessageStatusRequestUuidGetWithHttpInfo",
    value: function signMessageStatusRequestUuidGetWithHttpInfo(requestUuid) {
      var postBody = null;
      // verify the required parameter 'requestUuid' is set
      if (requestUuid === undefined || requestUuid === null) {
        throw new Error("Missing the required parameter 'requestUuid' when calling signMessageStatusRequestUuidGet");
      }
      var pathParams = {
        'request_uuid': requestUuid
      };
      var queryParams = {};
      var headerParams = {};
      var formParams = {};
      var authNames = ['RequestAuthorizer'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = _StatusResponse.StatusResponse;
      return this.apiClient.callApi('/sign-message/status/{request_uuid}', 'GET', pathParams, queryParams, headerParams, formParams, postBody, authNames, contentTypes, accepts, returnType);
    }
  }, {
    key: "signMessageStatusRequestUuidGet",
    value: function signMessageStatusRequestUuidGet(requestUuid) {
      return this.signMessageStatusRequestUuidGetWithHttpInfo(requestUuid).then(function (response_and_data) {
        return response_and_data.data;
      });
    }
  }]);
  return MessageSigningApi;
}();
exports.MessageSigningApi = MessageSigningApi;