"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.SatMetricsApi = void 0;
var _ApiClient = require("../ApiClient");
var _NextOnlineResponse = require("../model/NextOnlineResponse");
var _PublicKeysResponse = require("../model/PublicKeysResponse");
var _PublicRandomResponse = require("../model/PublicRandomResponse");
var _TimestampResponse = require("../model/TimestampResponse");
function _typeof(obj) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (obj) { return typeof obj; } : function (obj) { return obj && "function" == typeof Symbol && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }, _typeof(obj); }
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, _toPropertyKey(descriptor.key), descriptor); } }
function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); Object.defineProperty(Constructor, "prototype", { writable: false }); return Constructor; }
function _toPropertyKey(arg) { var key = _toPrimitive(arg, "string"); return _typeof(key) === "symbol" ? key : String(key); }
function _toPrimitive(input, hint) { if (_typeof(input) !== "object" || input === null) return input; var prim = input[Symbol.toPrimitive]; if (prim !== undefined) { var res = prim.call(input, hint || "default"); if (_typeof(res) !== "object") return res; throw new TypeError("@@toPrimitive must return a primitive value."); } return (hint === "string" ? String : Number)(input); } /*
                                                                                                                                                                                                                                                                                                                                                                                               * Cryptosat Sandbox
                                                                                                                                                                                                                                                                                                                                                                                               * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               * OpenAPI spec version: 1.0.0
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                               * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               * Swagger Codegen version: 3.0.46
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                               *
                                                                                                                                                                                                                                                                                                                                                                                               */
var SatMetricsApi = /*#__PURE__*/function () {
  function SatMetricsApi(apiClient) {
    _classCallCheck(this, SatMetricsApi);
    this.apiClient = apiClient || _ApiClient.ApiClient.instance;
  }
  _createClass(SatMetricsApi, [{
    key: "nextOnlineGetWithHttpInfo",
    value: function nextOnlineGetWithHttpInfo() {
      var postBody = null;
      var pathParams = {};
      var queryParams = {};
      var headerParams = {};
      var formParams = {};
      var authNames = ['RequestAuthorizer'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = _NextOnlineResponse.NextOnlineResponse;
      return this.apiClient.callApi('/next-online', 'GET', pathParams, queryParams, headerParams, formParams, postBody, authNames, contentTypes, accepts, returnType);
    }
  }, {
    key: "nextOnlineGet",
    value: function nextOnlineGet() {
      return this.nextOnlineGetWithHttpInfo().then(function (response_and_data) {
        return response_and_data.data;
      });
    }
  }, {
    key: "publicKeysGetWithHttpInfo",
    value: function publicKeysGetWithHttpInfo() {
      var postBody = null;
      var pathParams = {};
      var queryParams = {};
      var headerParams = {};
      var formParams = {};
      var authNames = ['RequestAuthorizer'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = _PublicKeysResponse.PublicKeysResponse;
      return this.apiClient.callApi('/public-keys', 'GET', pathParams, queryParams, headerParams, formParams, postBody, authNames, contentTypes, accepts, returnType);
    }
  }, {
    key: "publicKeysGet",
    value: function publicKeysGet() {
      return this.publicKeysGetWithHttpInfo().then(function (response_and_data) {
        return response_and_data.data;
      });
    }
  }, {
    key: "publicRandomGetWithHttpInfo",
    value: function publicRandomGetWithHttpInfo() {
      var postBody = null;
      var pathParams = {};
      var queryParams = {};
      var headerParams = {};
      var formParams = {};
      var authNames = ['RequestAuthorizer'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = _PublicRandomResponse.PublicRandomResponse;
      return this.apiClient.callApi('/public-random', 'GET', pathParams, queryParams, headerParams, formParams, postBody, authNames, contentTypes, accepts, returnType);
    }
  }, {
    key: "publicRandomGet",
    value: function publicRandomGet() {
      return this.publicRandomGetWithHttpInfo().then(function (response_and_data) {
        return response_and_data.data;
      });
    }
  }, {
    key: "timestampGetWithHttpInfo",
    value: function timestampGetWithHttpInfo() {
      var postBody = null;
      var pathParams = {};
      var queryParams = {};
      var headerParams = {};
      var formParams = {};
      var authNames = ['RequestAuthorizer'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = _TimestampResponse.TimestampResponse;
      return this.apiClient.callApi('/timestamp', 'GET', pathParams, queryParams, headerParams, formParams, postBody, authNames, contentTypes, accepts, returnType);
    }
  }, {
    key: "timestampGet",
    value: function timestampGet() {
      return this.timestampGetWithHttpInfo().then(function (response_and_data) {
        return response_and_data.data;
      });
    }
  }]);
  return SatMetricsApi;
}();
exports.SatMetricsApi = SatMetricsApi;